### PR TITLE
Fixing zip action creation

### LINKED ISSUE #273: Action created with .zip file fails with SyntaxError: Invalid or unexpected token
I tried a simple workflow here:

**1. Created an action for nodejs runtime**

```
cat index.js
function helloworld(params) {
    return {payload: 'Hello World!'};
}

exports.main = helloworld;
```

**2. Created zip file out of this single action file `index.js`:**

```
 zip helloworld.zip index.js
```

**3. Created manifest file with:**

```
package:
    name: helloworldzip
    actions:
        helloworld:
            location: src/helloworld.zip
            runtime: nodejs:6
```

**4. Deployed hello world action:**

```
bin/wskdeploy
         ____      ___                   _    _ _     _     _
        /\   \    / _ \ _ __   ___ _ __ | |  | | |__ (_)___| | __
   /\  /__\   \  | | | | '_ \ / _ \ '_ \| |  | | '_ \| / __| |/ /
  /  \____ \  /  | |_| | |_) |  __/ | | | |/\| | | | | \__ \   <
  \   \  /  \/    \___/| .__/ \___|_| |_|__/\__|_| |_|_|___/_|\_\
   \___\/              |_|

Packages:
Name: helloworldzip
    bindings:

  * action: helloworld
    bindings:
    annotations:


Triggers:

 Rules

Do you really want to deploy this? (y/N): y
2017/05/19 11:56:24 Deploying package helloworldzip ...
2017/05/19 11:56:25 Done!
2017/05/19 11:56:25 Deploying action helloworldzip/helloworld ...
2017/05/19 11:56:25 Done!

Deployment completed successfully.
```

**5. Invoke hello world action**

```
wsk action invoke helloworldzip/helloworld --blocking
ok: invoked <namespace>/helloworldzip/helloworld with id 15bdc301425b4c028df74311da45587a
{
    "activationId": "15bdc301425b4c028df74311da45587a",
    "annotations": [
        {
            "key": "limits",
            "value": {
                "logs": 10,
                "memory": 256,
                "timeout": 60000
            }
        },
        {
            "key": "path",
            "value": "<namespace>/helloworldzip/helloworld"
        }
    ],
    "duration": 45,
    "end": 1495220208672,
    "logs": [],
    "name": "helloworld",
    "namespace": "<namespace>",
    "publish": false,
    "response": {
        "result": {
            "error": "Initialization has failed due to: SyntaxError: Invalid or unexpected token\n    at NodeActionRunner.init (/nodejsAction/runner.js:75:109)\n    at doInit (/nodejsAction/src/service.js:133:31)\n    at initCode (/nodejsAction/src/service.js:81:24)\n    at /nodejsAction/app.js:61:13\n    at Layer.handle [as handle_request] (/nodejsAction/node_modules/express/lib/router/layer.js:95:5)\n    at next (/nodejsAction/node_modules/express/lib/router/route.js:131:13)\n    at Route.dispatch (/nodejsAction/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/nodejsAction/node_modules/express/lib/router/layer.js:95:5)\n    at /nodejsAction/node_modules/express/lib/router/index.js:277:22\n    at Function.process_params (/nodejsAction/node_modules/express/lib/router/index.js:330:12)"
        },
        "status": "action developer error",
        "success": false
    },
    "start": 1495220208627,
    "subject": "<namespace>",
    "version": "0.0.1"
}
```

Running the same with wsk CLI:

**Create an action:**

```
wsk action create helloworldzip helloworld.zip --kind nodejs:6
ok: created action helloworldzip
```

**Invoking hello world:**

```
wsk action invoke helloworldzip --blocking
ok: invoked /<namespace>/helloworldzip with id 27a1621dd8db430abeaade0ec1d33b0c
{
    "activationId": "27a1621dd8db430abeaade0ec1d33b0c",
    "annotations": [
        {
            "key": "limits",
            "value": {
                "logs": 10,
                "memory": 256,
                "timeout": 60000
            }
        },
        {
            "key": "path",
            "value": "<namespace>/helloworldzip"
        }
    ],
    "duration": 72,
    "end": 1495222791850,
    "logs": [],
    "name": "helloworldzip",
    "namespace": "<namespace>",
    "publish": false,
    "response": {
        "result": {
            "payload": "Hello World!"
        },
        "status": "success",
        "success": true
    },
    "start": 1495222791778,
    "subject": "<namespace>",
    "version": "0.0.1"
}
```

Tried with different combination of keys in manifest file but fails with same error:

**Without explicitly specifying runtime:**

```
package:
    name: helloworldzip
    actions:
        helloworld:
            location: src/helloworld.zip
```

**With `kind` keyword (not sure if its supported, looking into it):**

```
package:
    name: helloworldzip
    actions:
        helloworld:
            location: src/helloworld.zip
            kind: nodejs:6
```

@mrutkows @lzbj @houshengbo @daisy-ycguo

### PR DESCRIPTION
**Pull request by pritidesai**
Base64 encoding zipfile content so that action payload is sent in expected format via HTTP request.

Also, added integration test for a simple zip action.

Fixes #273

### CODE REVIEW

File: tests/src/integration/zipaction/zipaction_test.go [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+	"github.com/apache/incubator-openwhisk-wskdeploy/tests/src/integration/common"
+	"github.com/stretchr/testify/assert"
+	"os"
+	"testing"
+)
+
+
+var wskprops = common.GetWskprops()
+
+// TODO: write the integration against openwhisk
```
Comment (mrutkows) [inline tests/src/integration/zipaction/zipaction_test.go]: @pritidesai What is left to do here?  If there is more to be done I assume another issue or PR will be incoming.  i would like to get the base64 encoding merged in the meantime.

File: parsers/manifest_parser.go [hunk 2]
```diff
@@ -262,6 +257,15 @@ func (dm *YAMLParser) ComposeActions(mani *ManifestYAML, manipath string) (ar []
 				}
 
 				wskaction.Exec.Kind = kind
+
+				action.Location = filePath
+				dat, err := utils.Read(filePath)
+				utils.Check(err)
+				code := string(dat)
+                		if ext == ".zip" || ext == ".jar" {
```
Comment (mrutkows) [inline parsers/manifest_parser.go]: @pritidesai Did we want to include a JAR test case?  It would be a good idea for coverage; please open another issue if you do not want to fix here.

**Comment by lzbj** [comment]
@pritidesai , could you please reply matt's comments, then we can merge this pr?

File: parsers/manifest_parser.go (hunk 2 above)
Comment (pritidesai) [inline parsers/manifest_parser.go]: I tested JAR with HelloWorld application from [here](https://console.ng.bluemix.net/docs/openwhisk/openwhisk_actions.html#openwhisk_actions_java). We do not have support for this application. wskdeploy fails with:

```
Response body received:
{
  "error": "The request content was malformed:\n'main' must be a string defined in 'exec' for 'java' actions",
  "code": 4001042
}
``` 

For actions in Java runtime, wsk CLI supports "--main" param which (I assume) might not be supported in wskdeploy. While creating an action from the jar file where main is inside of a class, we have to specify the class name which contains main function.

```
wsk action create helloJava hello.jar --main Hello
``` 

I am using this manifest file:

```
package:
    name: helloworldjar
    actions:
        helloworld:
            location: src/hello.jar
            runtime: java
            main: Hello
```

I am creating separate issue to address JAR failure.

Comment (pritidesai) [inline parsers/manifest_parser.go]: Created separated issue for JAR: #276

**Comment by mrutkows** [comment]
@lzbj @pritidesai I am fine merging this if David can review/approve the base64 encoding change since we have another issue to work on "JAR" file problem in the future.
